<a href="https://colab.research.google.com/github/DBCooper200/project/blob/main/linearregressionusingmultiplevariables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

multi variable linear regression goes by the following formula
output=(m1*feature1)+(m2*feature2)+(m3*feature3).....+intercept
output is dep var
features are inputs which maybe missing at some point
linear regression can be applied if there is a linear relation between every feature and output it could be an inverse relationship
independent variables are called features
in our example 
price=(m1*area)+(m2*rooms)+(m3+age)+b

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [5]:
df=pd.read_csv("arearoomagevsprice.csv")

In [6]:
df

area  rooms  age   price
0  2600    3.0   20  550000
1  3000    4.0   15  565000
2  3200    NaN   18  610000
3  3600    3.0   30  595000
4  4000    5.0    8  760000

as data points r missing we calculate median

In [8]:
df.rooms.median()

3.5

In [12]:
import math
rooms_median=math.floor(df.rooms.median())
df.rooms=df.rooms.fillna(rooms_median)
df

area  rooms  age   price
0  2600    3.0   20  550000
1  3000    4.0   15  565000
2  3200    3.0   18  610000
3  3600    3.0   30  595000
4  4000    5.0    8  760000

data processing complete

In [14]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','rooms','age']],df.price)

LinearRegression()

In [29]:
val=[3000,3,40]
reg.predict([val])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [30]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [31]:
reg.intercept_

383724.99999999994

In [32]:
(val[0]*reg.coef_[0])+(val[1]*reg.coef_[1])+(val[2]*reg.coef_[2])+reg.intercept_

444400.00000000006

In [33]:
df1=pd.read_csv("arearoomsage.csv")
df1

area  rooms   age
0   2500    2.0  15.0
1   2900    NaN  12.0
2   3000    2.0   5.0
3   3100    NaN  21.0
4   7000    5.0   NaN
5   2300    NaN  10.0
6   4300    3.0   4.0
7   5000    4.0   NaN
8   5400    3.0   2.0
9   5500    3.0  16.0
10  1500    2.0  12.0

In [34]:
df1.rooms=df1.rooms.fillna(math.floor(df1.rooms.median()))
df1.rooms

0     2.0
1     3.0
2     2.0
3     3.0
4     5.0
5     3.0
6     3.0
7     4.0
8     3.0
9     3.0
10    2.0
Name: rooms, dtype: float64

In [35]:
df1.age=df1.age.fillna(math.floor(df1.age.median()))
df1.age

0     15.0
1     12.0
2      5.0
3     21.0
4     12.0
5     10.0
6      4.0
7     12.0
8      2.0
9     16.0
10    12.0
Name: age, dtype: float64

data preprocessed

In [36]:
reg.predict(df1)

array([ 572425.,  621775.,  709300.,  587800., 1132450.,  553075.,
        868525.,  883975., 1033150.,  951325.,  455650.])

In [37]:
df1['price']=reg.predict(df1)

In [38]:
df1.to_csv("predictions.csv")